version: '2'
volumes:
    resin-data:
services:
  box:
    build:
      context: .
      dockerfile: ./compose/box/Dockerfile
    depends_on:
      - redis
    volumes:
      - resin-data:/tmp
      - resin-data:/var/log/nginx
    command: ["python", "/app/run_box.py"]

  redis:
    image: mangoraft/redis-arm
    environment:
      - REDIS_PASS=**None**

  nginx:
    build:
      context: .
      dockerfile: ./compose/box/nginx/Dockerfile
    volumes:
      - resin-data:/tmp
      - resin-data:/var/log/nginx
      - resin-data:/etc/localtime
    ports:
      - "7070:7070"
      - "7072:7072"
    depends_on:
      - box
